### ISSUE TITLE
MediaManager Tree items wrong formatted

### ISSUE THREAD

**Issue by rjahn** [LeonStaufer/material-dokuwiki#11]
The Media Manager shows a tree, but the items are "multi-line". The icon is in line 1 and the text is in line 2. 

The text should be beside the +/- icon.

**Comment by rjahn** [comment]
fixed with following styles in basic.less:

    #mediamanager__page li div.li {
      display: initial;
      padding-left: 7px;  
    }

    #mediamanager__page ul.thumbs li dt {
      padding-bottom: 18px;
    }

    #mediamanager__page ul.thumbs li dd {
      margin-left: 0;
    }

**Comment by LeonStaufer** [comment]
Thanks for the feedback.

I feel that the media manager is in need of a visual overhaul anyway, so this is a great addition to that.
If you have any suggestions on how you think it should look, please contribute :)

**Comment by rjahn** [comment]
The whole mediamanager is horrible. If you add lots of images, the empty space grows and the page is too heigh.

The media info page for e.g. image links is also horrible because the template doesn't work. Same problem for media upload.

Currently, I didn't check the source code, so a contribution isn't possible :)

**Comment by LeonStaufer** [comment]
Yea, I'm sorry about that. I originally developed the template for a project of mine for which I didn't require the media manager, so when I put little time into working on it back then. 

Now that it is a public template, I have started to refine many aspects, and I am aware that the media manager definitely needs to be improved.

Unfortunately, I currently don't have the time to redesign it, so an update to the media manager might take a while :/
