### ISSUE TITLE
No new page button for searched articles

### ISSUE THREAD

**Issue by glitchroy** [LeonStaufer/material-dokuwiki#13]
When you try to directly add a new article that doesn't exist (`/wiki/blabla`), the template offers the option to add the article (the plus button with `/wiki/blablabla?do=edit` to the right).  
If you search for an article (page ``/wiki/doku.php?do=search&id=Blabla``) however, no button control to the right is present.  
It would be nice to be able to add a new article without having to edit the url directly.

**Comment by LeonStaufer** [comment]
Thanks for the feedback.

I agree that there should be the option to create a page from search and I'll work on adding that to the next update.

For now, you can click on the name of your query which will bring you to its page. From there you can create it as normal. 

![Screenshot of search page](https://s9.postimg.org/ptjgaboy7/search.png)
