### ISSUE TITLE
php Warning in main.php

### ISSUE THREAD

**Issue by clavicarius** [LeonStaufer/material-dokuwiki#16]
line 105 in main.php gives a warning:
Use of undefined constant php - assumed 'php' (this will throw an Error in a future version of PHP) in
/var/web/public_html/dokuwiki/lib/tpl/material/main.php on line 105

the reason is the comment marker "//" - so the closing "?>" php-bracket will be ignored.

**Comment by LeonStaufer** [comment]
Thank you. I believe this should have fixed it
