### ISSUE TITLE
Sidebar configuration

### ISSUE THREAD

**Issue by amirix** [LeonStaufer/material-dokuwiki#17]
First thing first - thank you for a great looking template!

We have installed the template from the extension manager and made sure to install the latest version (6/2/18).

As the sidebar is a very important part of the navigation and UX, I am now trying to edit the default sidebar, but cannot find the way to do so. In the GitHub project page I can see the file sidebar.php, but it does not exist in the downloaded template. I have tried to upload it next to the main.php, but that did not help as well.

I did notice that the files here in GitHub are newer than the apparently latest stable release of 6/2.  it seems that at least main.php is different as well between here and the downloaded version.

Thanks

**Comment by sajidrs** [comment]
I could find the sidebar.php and I downloaded from extension manager. Are you sure you are checking in the correct directory? 
I have even successfully managed to edit the sidebar.php.

**Comment by LeonStaufer** [comment]
Thanks for your feedback. I'll look into it.

I don't understand why there is no `sidebar.php` file in your installation. Does reinstalling the template fix the issue?

Otherwise, you are right, the `main.php` here is newer. I have not pushed these updates yet though, because I did not feel they warranted an entirely new release.

**Comment by amirix** [comment]
Thanks for taking the time to have a look and comment.
I re-checked and re-installed, the problem is solved and the file is found, I have no idea what went wrong before.
Cheers!

**Comment by LeonStaufer** [comment]
Okay. I'm glad to hear it works now.
I'll close the issue and enjoy the template!
