### ISSUE TITLE
PDF Export Integration

### ISSUE THREAD

**Issue by MobFactory** [LeonStaufer/material-dokuwiki#19]
I have noticed that this template lacks the automatic support for dw2pdf. Could you please add it?

**Comment by LeonStaufer** [comment]
Okay, thank you for letting me know. I will add it for the next release.

**Comment by LeonStaufer** [comment]
More information, for development:
https://www.dokuwiki.org/plugin:dw2pdf:pagetool
https://www.dokuwiki.org/devel:menus
https://www.patreon.com/posts/menus-14160215
