### ISSUE TITLE
Search box redirects to hard coded /dokuwiki/doku.php

### ISSUE THREAD

**Issue by GJRobert** [LeonStaufer/material-dokuwiki#2]
Hi there,

This template is elegant and yet feature rich, I love it! Thank you so much for releasing!

Here is what I have seen using the search box (after typing the keyword and hitting Enter):
```
Not Found

The requested URL /dokuwiki/doku.php was not found on this server.
```
I had renamed my DokuWiki folder to simply "/dw" since I started to use DokuWiki, so I guess this is why the template does not find doku.php in /dokuwiki.

**Comment by LeonStaufer** [comment]
Hello,

Thank you for pointing this out. I did hardcode the URL (not a very good practice at all, unfortunately) and didn't consider the implications for people who have renamed the folder. I will try and find a more elegant solution to this.

Greetings,
Leon

**Comment by LeonStaufer** [comment]
The latest update should have fixed this issue. Please let me know if you encounter any other problems.

Enjoy :)

**Comment by GJRobert** [comment]
Hi Leon,

Thank you so much for fixing this! Great news!

Ciao!
