### ISSUE TITLE
Sidebar should use DokuWiki's sidebar config

### ISSUE THREAD

**Issue by takuy** [LeonStaufer/material-dokuwiki#20]
This template would be way better if it were able to use Dokuwiki's sidebar config, rather than it's own file.

**Comment by MobFactory** [comment]
Agreed

**Comment by LeonStaufer** [comment]
It took me a while to understand what you mean, but I assume you are referred to the option for the sidebar to be a rendering of the dokuwiki sidebar page as described [here](https://www.dokuwiki.org/config:sidebar).

This template already has this functionality, it was added as a response to issue #15.
You can enable this by changing `$sidebarPage = false;` to `true` in the `sidebar.php` file on line 13.

**Comment by LeonStaufer** [comment]
As there have been no further replies, I think the issue is resolved.
