### ISSUE TITLE
Tables don't look right.

### ISSUE THREAD

**Issue by MobFactory** [LeonStaufer/material-dokuwiki#21]
As you can see in my example http://learnib.org/wiki/doku.php?id=wiki_formatting_guidelines tables look weird and dont have any borders between cells.

**Comment by LeonStaufer** [comment]
I gladly look into it. However, I could not find a table on the website you shared.

**Comment by MobFactory** [comment]
It's there, if you look under the heading: Short-cut keys for CKGEDIT (Page Editor). It just doesn't look like a table because something isn't right. Thanks for your help

**Comment by LeonStaufer** [comment]
Okay thanks. I see what you mean. I assume that `reset.css` removed the table borders and that I haven't added any custom material styling yet.

I'll add it for the next release.

**Comment by MobFactory** [comment]
Thanks
