### ISSUE TITLE
After theme was set every wiki page became blank

### ISSUE THREAD

**Issue by ivujosevic** [LeonStaufer/material-dokuwiki#25]
I've installed the theme using the Extension Manager and when I enabled the theme my wiki refreshed and now every single page looks like this:
<img width="1440" alt="screen shot 2018-09-10 at 18 01 37" src="https://user-images.githubusercontent.com/17006954/45309309-baf68100-b523-11e8-9e78-1ae27029a636.png">
I can't even revert the changes since I can see the settings page.

**Comment by LeonStaufer** [comment]
Thank you for your bug report. Unfortunately, I was not able to reproduce the issue. 
Are there any error messages or console logs?
