### ISSUE TITLE
Modify mdl-btn

### ISSUE THREAD

**Issue by AureleCollinet** [LeonStaufer/material-dokuwiki#26]
Hello,

I wish to add an link and an icon to the 

![capture](https://user-images.githubusercontent.com/35695327/50834884-781fab00-1355-11e9-9a4f-a77a751aedad.PNG)

i wish to know of its possible with your template and what do i need to change in the code for it

**Comment by LeonStaufer** [comment]
Yea that's possible.

If you look at the `main.php` on line 57 you can see how we create the buttons in the header.

Each button is essentially the following:
```html
<button class="mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect mdl-button--colored">
    <i class="material-icons">icon_name</i>
</button>
``` 
To make it a link, just wrap it inside a `<a href="link">` tag. You can specify the type of icon by replacing `icon_name` by any icon name from the [Material Icon set](https://material.io/tools/icons/).

You can add this after line 92 in the `main.php` file.

**Comment by AureleCollinet** [comment]
Thanks a lot
