### ISSUE TITLE
Issue Media manager

### ISSUE THREAD

**Issue by AureleCollinet** [LeonStaufer/material-dokuwiki#27]
Hello, i got an issue with the media manager, its looking pretty wierd. The media list dont stay in the page container and keeps going in the footer of the page.

**Comment by LeonStaufer** [comment]
Thanks for your feedback. Could you please post an image of the problem?

**Comment by AureleCollinet** [comment]
![hugespace](https://user-images.githubusercontent.com/35695327/51922151-c4a45680-23e8-11e9-94af-3b941ddaf8f1.PNG)
here you can see the big blank area i didn't spoke of
![pbmedia1](https://user-images.githubusercontent.com/35695327/51922171-cd952800-23e8-11e9-87bf-c85d1afc1321.PNG)
and here is the "main" problem

**Comment by LeonStaufer** [comment]
Thank you. I've been able to reproduce the issue, and it's very weird. For some reason, there is a hardcoded height for some panels in the media manager. To fix it, we set `height: auto`.

Adding the following to `css/fixes.less` resolves the problem:
```css
//media manager styling fix
.panel, .panelContent {
    height: auto !important;
}
```

You can either do this yourself or update the theme with the next release.
