### ISSUE TITLE
Page content not displayed as cards

### ISSUE THREAD

**Issue by sh1989** [LeonStaufer/material-dokuwiki#29]
Using a clean install of DokuWiki Greebo and latest Material template (2019-29-01) with no customisations, on latest Firefox and latest Edge, it appears that the card layout styles are not correctly being applied. Notice there is no margin or borders on page-content. The default image also extends beyond the sidebar. The action buttons to edit and show history do not float to the right.

I can't test in Chrome because I don't have it installed on my machine unfortunately.

![dokuwiki-material](https://user-images.githubusercontent.com/2462285/52915080-97e8ae00-32c7-11e9-8bfb-a2bdd6b229dd.jpg)

**Comment by sh1989** [comment]
I'm going to close this, as the problem wasn't actually the extension or DocuWiki... it was the default settings of my webhost that were fighting against me.

For anyone else who sees this problem, make sure that you ensure the file access permissions are adequately set in your DocuWiki dir (even better, your public_html) folder.  I discovered this by noticing jQuery wasn't loading correctly, and the web server had the following error:

```
[Sun Feb 17 15:52:03.135700 2019] [:error] [pid 75383] SoftException in Application.cpp:651: Directory "/home/public_html/wiki/lib" is writeable by group
```

This did the trick for me:
`chmod 755 -R public_html/`

Now everything looks as expected... phew!

**Comment by LeonStaufer** [comment]
Thank you for the advice.
