### ISSUE TITLE
De-emphasize canonical page names

### ISSUE THREAD

**Issue by SpencerDub** [LeonStaufer/material-dokuwiki#31]
I really adore this theme. Thanks for your great work on it.

One minor issue I've found is that the theme strongly emphasizes page names by rendering them as top-level headers at the top of the page. This is less than ideal in cases when the limitations of DokuWiki page naming conventions (all lowercase, spaces converted to underscores, etc.) conflict with the intended title of a page. For instance, I have a page whose name is supposed to be "Server Setup Log", but whose canonical DokuWiki pagename is "Server_setup_log". The latter is displayed prominently at the top of the page in a large `<h1>` header.

The default DokuWiki theme deals with this by de-emphasizing (but still displaying) the page's actual name--for example, see the [pagename](https://www.dokuwiki.org/pagename) page. Users can then set a preferred title in the page editor simply by using the appropriate Markdown tags.

I'd like to suggest that the Material theme follow this convention and de-emphasize the canonical page name, allowing for users to define top-level page titles in the content of a page.

**Comment by SpencerDub** [comment]
I hacked around in my browser's DOM editor and made this quick mockup of what this could look like. In this image, "DIY Cleaner Recipes" is a top-level heading defined in the text of the page, whereas "cleaner-recipes" is the canonical page name.

![DokuWiki material deemphasized pagename](https://user-images.githubusercontent.com/4674927/71536890-800b8e80-28c9-11ea-9813-154fa9d209e4.png)

**Comment by LeonStaufer** [comment]
Thank you for your kind words, I'm glad you are enjoying the theme.

I appreciate your suggestion and was facing a similar problem when I was using DokuWiki. I was able to resolve it nicely by using the [pagetitle plugin](https://www.dokuwiki.org/plugin:pagetitle). With it, you can specify the page title that is supplied by DokuWiki during rendering. Another alternative would be to use the [meta plugin](https://www.dokuwiki.org/plugin:meta) and specify the meta title tag.

Although, I must admit that neither is a very elegant solution. If you'd like to add your suggestion, I would gladly accept a pull request.

**Comment by SpencerDub** [comment]
Thanks for the tips, Leon. I installed the pagetitle plugin like you suggested, but whether I define the title using the `<title>Foobar</title>` or `~~Title: Foobar~~` syntax, the theme still displays the canonical pagename prominently at the top of the page content. (Within the browser viewport, I mean--I'm not referring to the title in the browser's titlebar.) Do you mind sharing how you use the pagetitle plugin?

My primary concern right now is not the literal `<title>` of the page, but rather the [pagename](https://www.dokuwiki.org/pagename), which Material currently renders as a prominent `<h1>`. Fixing the `<title>` is important too, but my main interest is finding a way to de-emphasize the pagename in Material so that I can write whatever title I want at the top of each page.

In an image, here's what I'm concerned with right now:
![DokuWiki Material page titles](https://user-images.githubusercontent.com/4674927/71636508-3c28ca00-2be6-11ea-93e8-6f370bc63e6f.png)

At any rate, I'm happy to try to put a pull request together, but my PHP is very rusty, and my CSS is often rather hacky! My example in my reply above, for instance, didn't change any of the wrapper `<div>`s because I don't know the logic behind the document structure; I just replaced the `<h1>` tags with `<span>`s or something like that, and hacked some CSS together in the browser. If you have beautiful, logical code, any pull request I might make would likely be like a bull in a china shop.

That said, if you want to use my work as a starting point, I'm happy to try making a pull request to address this! :)

**Comment by LeonStaufer** [comment]
If I recall correctly, you can choose which title to display with the `useheading` property in the DokuWiki configuration. With that enabled it should use the first heading of the document as the title.
Please let me know if that works.

Also thank you for your work on #32, don't worry if the CSS is hacky, mine is too :)

**Comment by LeonStaufer** [comment]
Turns out, it wasn't the `useheading` property - which would have made sense - but instead, the `youarehere` property as you can see [here](https://github.com/LeonStaufer/material-dokuwiki/blob/master/main.php#L204).

So I think that if you use the pagetitle plugin, you can manage to at least display the correct title.

![Screenshot of title](https://user-images.githubusercontent.com/30228998/78836993-7975d280-79f3-11ea-8203-378eeef62362.png)

However, if I understand you correctly, you would also like the option of making the title less prominent, so I would say the issue still persists.

**Comment by SpencerDub** [comment]
This is great, @LeonStaufer, thank you!
