### ISSUE TITLE
Action unknown: menuitem

### ISSUE THREAD

**Issue by tools400** [LeonStaufer/material-dokuwiki#33]
Hi Leon,

I just gave your "Material" theme a try and in fact I loved it right from the beginning. Sadly there is a problem with the ["Move Plugin"](https://www.dokuwiki.org/plugin:move) which I find is very useful, too.

Whenever I click the "Move" option on whatever page I get the "Action unknown: menuitem" and the menu item vanishes until the page is reloaded.

Do you have an idea how to fix that?

Regards,

Thomas.

**Comment by LeonStaufer** [comment]
Thank you, Thomas. 

I'll have to take a closer look at the plugin some time to understand why this happening. During a quick search for the issue, I discovered the [following issue #150](https://github.com/michitux/dokuwiki-plugin-move/issues/150) in the plugin move repository. Does the issue persist if you use the regular/desktop view?

**Comment by tools400** [comment]
Thank you for your fast reply. I still test and play with the Wiki and I did not yet give it a try on a mobile device. So the answer is: yes, it happens in the regular/desktop view.

![material_theme_problem_2](https://user-images.githubusercontent.com/3110562/78297510-03bfc180-7530-11ea-829b-b3634417e126.jpg)
![material_theme_problem_1](https://user-images.githubusercontent.com/3110562/78297514-04f0ee80-7530-11ea-9378-0cf3ba1c65d2.jpg)

**Comment by LeonStaufer** [comment]
Good news, I have been able to fix the issue. 

Could you please manually update the `main.php` file because I don't think I'm ready to release a new version entirely yet. 

Let me know if it works :)

**Comment by tools400** [comment]
Hi Leon,
Good work! That did the trick.
Thanks,
Thomas.

**Comment by WikICAM** [comment]
@LeonStaufer I have got the "Action unknown: menuitem" how can i manually update the main.php ?

**Comment by LeonStaufer** [comment]
In case it's the same problem, it should be sufficient if you replace the `main.php` file in your template folder with the most recent one here on GitHub.

**Comment by WikICAM** [comment]
@LeonStaufer Sorry for my question but where can i find the most recent one on GitHub and where should I replace it ? In the main.php who is in the file /lib/tpl/bootstrap3 ?

**Comment by LeonStaufer** [comment]
The most recent one is just the file in the master branch, so [this one](https://raw.githubusercontent.com/LeonStaufer/material-dokuwiki/master/main.php).

Then you should replace the `main.php` file in your material template folder, most likely at `lib/tpl/material`.

I hope this helps.

**Comment by WikICAM** [comment]
@LeonStaufer To understand, I'm currently using the 'Boostrap3' template so I download the `main.php` and replace it in the lib/tpl/bootstrap3 folder ? 
I did this but it doesn't works and the layout of my site is totally different

**Comment by LeonStaufer** [comment]
This `main.php` file won't work with the bootstrap template. You'll need to replace it in the material template folder.

I'm unsure what you're trying to do, maybe you could open a new issue and please explain it there.

**Comment by WikICAM** [comment]
@LeonStaufer I am new in Github how can i open a new issue

**Comment by LeonStaufer** [comment]
Please take a look at the following [guide by GitHub](https://docs.github.com/en/issues/tracking-your-work-with-issues/quickstart).
