### ISSUE TITLE
Problem loading external script

### ISSUE THREAD

**Issue by jgmac1106** [LeonStaufer/material-dokuwiki#34]
Hello, I am trying to use this https://github.com/PlaidWeb/webmention.js/ seems to work in all the other dokuwiki themes I try but I can't seem to load the script at all

here is an example: https://longthoughts.jgregorymcverry.com/doku.php?id=namespace:test_post#enter_doku_wiki

I tried adding the javascript to the existing file and making a new file:, links from my head:
 <link rel="pingback" href="https://webmention.io/jgregorymcverry.com/xmlrpc" />
<link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
<link href='https://longthoughts.jgregorymcverry.com/lib/tpl/codowik/css/webmention.css' rel='stylesheet' type='text/css'>
<script src="https://longthoughts.jgregorymcverry.com/lib/tpl/material/js/webmention.js" async></script>

Do I need to do anything to authorize external scripts?

**Comment by LeonStaufer** [comment]
Thank you. I've tried to reproduce your issue but I'm having some difficulties.

Which of the [suggested ways of loading JavaScript](https://www.dokuwiki.org/devel:javascript) are you using?

**Comment by jgmac1106** [comment]
I can close this, I was able to get it loading.

**Comment by LeonStaufer** [comment]
Okay, thank you. How did you manage to load it?
