### ISSUE TITLE
Template config options are without useful description

### ISSUE THREAD

**Issue by yusurko** [LeonStaufer/material-dokuwiki#36]
The image below is self explanatory. Tested with both Italian and English locale.

![Schermata da 2020-04-27 13-19-12](https://user-images.githubusercontent.com/48103762/80366563-c2e66e80-8889-11ea-941a-05e1f627db91.png)

**Comment by LeonStaufer** [comment]
Thank you for the suggestion.

In the meantime, you can take a look at the [configration section](https://github.com/LeonStaufer/material-dokuwiki#configuration) in the readme.
