### ISSUE TITLE
Is it possible to change the position of TOC?

### ISSUE THREAD

**Issue by dylan00j** [LeonStaufer/material-dokuwiki#38]
love the design thanks
I wonder whether I can change the position and size of the TOC?
I'd prefer it smaller and up to Right, possibly even floating?
many thanks
Dylan

**Comment by LeonStaufer** [comment]
Thanks. That's definitely possible but I probably won't provide that additional functionality for this template.

If you want to change the size of the TOC, you could add your own CSS rule to `<dokuwiki>/conf/userstyle.css`. 
Changing the position is a little harder. I would suggest editing the `main.php` around line [217](https://github.com/LeonStaufer/material-dokuwiki/blob/master/main.php#L217) to change `tpl_content();` to  `tpl_content(false);`. That will exclude the TOC from the main content. To add it back, use ` tpl_toc()` anywhere you like.

Here is quote from the [DokuWiki docs](https://www.dokuwiki.org/devel:templates#tpl_toc):
> By default, the tpl_content() function will take care of displaying a Table of Contents itself, prepending it to the actual page content. If your template uses a sidebar or other more complex layout you may want to place the TOC independently from the page content. This can be done with the tpl_toc() function. When using it, it is important to disable automatic TOC placement by passing the argument false to the tpl_content() function.

**Comment by dylan00j** [comment]
many thanks Leon
I will try to figure this out now based on that.
Bit new to this but hopefully I'll learn a little more!
thanks again
Dylan

**Comment by LeonStaufer** [comment]
Glad to hear and let me know if you need any more help.

**Comment by dylan00j** [comment]
Thanks so much.
I'll delve 1st and see if I can figure it out myself and get back to you if
I can't!
Fingers crossed
Dylan
