### ISSUE TITLE
configure of style.ini not applied

### ISSUE THREAD

**Issue by SwayYe** [LeonStaufer/material-dokuwiki#39]
After uncommenting  the color preset in “replacements” section in style.ini,
I refreshed the page in the browser and failed to find the page theme changed.
```
; Blue - Pink
 __primary__         = "#3F61b5"             ; @ini_primary
 __primary_dark__    = "#303f9f"             ; @ini_primary_dark
 __accent_           = "#ff4081"             ; @ini_accent
```
Am I not doing this rightly?

**Comment by LeonStaufer** [comment]
This is should work as long as you comment out the previous values as well.

The better solution would be to use the style configuration within the DokuWiki administration panel. That way, you can directly specify color values.

Another possible solution might be to flush the cache and force reloud the web page. Let me know if that works.

**Comment by SwayYe** [comment]
I configured the style within the DokuWiki administration panel and that works!
It seems that the value in the administration panel will dominate any modification in stylle.ini.
Thanks a lot for your help!
