### ISSUE TITLE
[bug] small wiki pages occupy smaller height before occupying viewport height

### ISSUE THREAD

**Issue by mkrtchian** [LeonStaufer/material-dokuwiki#50]
When a wiki page has not enough content, the main content starts as smaller than the normal height, and occupies the normal height after some time. That time is linked to the use of `defer` on material script [here](https://github.com/LeonStaufer/material-dokuwiki/blob/fec94ce85706a77ca877bf60109c754a9b5f2eaa/main.php#L34).

If we want to keep the `defer` we may add some CSS to force the main content having the correct height from the beginning.

Here is a gif showing the visual bug :

![height_defer_bug](https://user-images.githubusercontent.com/6060774/95682997-d9d70e00-0be8-11eb-8232-5b7a00bc20f6.gif)

**Comment by LeonStaufer** [comment]
I agree that we defintely need to keep the `defer` and I think the solution you proprosed solves the issue sufficiently well.
