### ISSUE TITLE
How to add additional right side buttons?

### ISSUE THREAD

**Issue by poVoq** [LeonStaufer/material-dokuwiki#6]
First off: very nice theme, thanks for creating!

I would like to use plugins like the comments, the .odt export and the .pdf export plugins with this theme that are usually accessible through these floating buttons on the right side. However this theme only provides the edit and revisions button.

Any way to add new buttons for plugins or include some additional buttons for popular Dokuwiki plugins out of the box?

I guess they are not enabled by default because the buttons are so big? Maybe there could be a big (...) button to pop up additional options for the above plugins? But comments could probably have their own big button :)

**Comment by LeonStaufer** [comment]
I definitely agree that having only two main buttons limits the functionality currently.

If you need to quickly add support for other plugins you can _easily_ add another button. All you need to do is add the following code to the `main.php` file after line 119:

``` php
<div class="content-actions__action">
    <?php tpl_action('action', true, false, false, '', '', "
        <button class=\"mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored content-actions__action-button\">
            <i class=\"material-icons\">icon</i>
        </button>") ?>
</div>
```

Make sure to replace `action` with your desired action and `icon` with a material icon of your choice.

Adding native support to the template for various actions is on my to-do list, but more of a long-term goal.
