### ISSUE TITLE
Respect Dokuwiki sidebar setting

### ISSUE THREAD

**Issue by poVoq** [LeonStaufer/material-dokuwiki#7]
In Dokuwiki under basic settings there is the option to switch or disable the sidebar:
`Sidebar page name (if template supports it), empty field disables the sidebar`

I tried disabling the sidebar through it, but it doesn't seem to have an effect.

Somewhat related: is it possible to easily have different sidebars for different wiki animals (farmer plugin)?

**Comment by LeonStaufer** [comment]
Thanks for the feedback. That is a very good point. 
I will try and fix this issue with the next update.

Unfortunately, due to time constraints, I probably won't be able to support the farmer plugin. If you wish, you can make a pull request and contribute though :)
