### ISSUE TITLE
Support translations plugin?

### ISSUE THREAD

**Issue by poVoq** [LeonStaufer/material-dokuwiki#8]
The translations plugin seems to be more or less a core feature of Dokuwiki, but currently the top side button to switch languages is not supported by this theme I think. Would be great if that could also be added.

Thanks!

**Comment by LeonStaufer** [comment]
I completely agree. This is a core functionality of DokuWiki and should be accessible in the template.
I'll try and work on adding this as soon as I can, but in the meantime, feel free to contribute if you wish.
