### ISSUE TITLE
Log out option?

### ISSUE THREAD

**Issue by poVoq** [LeonStaufer/material-dokuwiki#9]
Seems like there is no option for a user to log out? Or is it very hidden?

I guess the user button should give a drop-down like other themes do it?

**Comment by rjahn** [comment]
We changed our the main.php to solve the problem:

    <?php
    if ($INFO['userinfo'] != null) 
    {
      tpl_action('login', true, false, false, '', '', "
        <button class=\"mdl-button mdl-js-button mdl-button--icon mdl-js-ripple-effect mdl-button--colored\">
          <i class=\"material-icons\">exit_to_app</i>
        </button>");
    } 
    ?>

simply add this code after the other tpl_action calls.
